# https://developers.cloudflare.com/pages/configuration/build-configuration/
[build]
  command = "npm run build && npx @cloudflare/next-on-pages"
  destination = ".vercel/output/static"

[build.environment]
  NODE_VERSION = "22"
  NEXT_TELEMETRY_DISABLED = "1"
